### ISSUE TITLE
Compatibility with gallery

### ISSUE THREAD

**Issue by tlegras** [pakerfeldt/android-viewflow#24]
Hi
I have a gallery in the views for which I would like to use ViewFlow. Unfortunately the fling event over the gallery are intercepted by the ViewFlow. is there any way to avoid that?
Thierry

**Comment by pakerfeldt** [comment]
I'm not entirely sure what you're after. Do you want to be able scroll horizontally both in ViewFlow and in Gallery? That is not considered good practice and would probably confuse the user. 

On a technical level, the ViewFlow will get the touch event before the gallery, and since ViewFlow supports horizontal scrolling it will consume the event.

**Comment by tlegras** [comment]
Thanks for your quick reply, 
Yes you're right but the gallery is one a small component at the bottom of the views, so I was thinking it would not be a problem for the users.
Okay may be I have either to consider another solution for switching views or for the gallery. 
Anyway your implementation of viewflow with adapter pattern and also the title indicator is really brilliant. Thanks for sharing it.

Thierry

**Comment by pakerfeldt** [comment]
I was actually wrong, the gallery view will get the touch event before the ViewFlow but for some reason it does not consume it. This indicates that ViewFlow identifies the horizontal action earlier than gallery. It could possibly be fixed by increasing the distance needed to travel on the screen before ViewFlow consumes the event. 

You could try to increase the value of mTouchSlop in ViewFlow.java and see if that changes things. We currently get the distance needed to travel by reading from ViewConfiguration. I would guess the gallery widget would do the same but apparently ViewFlow consumes the event before.

Issue #14 is quite similar.

**Comment by tlegras** [comment]
Year you must be right as in some cases the gallery seems to get the event.
On the other hand I think I you follow your first suggestion and remove the gallery. Indeed I use it as an extensible button bar and I am no consider replace it by a quick action pattern. 
So for me the issue is closed :)
Thanks.
Thierry.
